### ISSUE TITLE
Bobbin not detecting arm-none-eabi-gcc

### ISSUE THREAD

**Issue by OtaK** [bobbin-rs/bobbin-cli#8]
Hey,

I'm setting up and embedded toolchain and I've noticed that bobbin is not able to find my gcc.

I noticed that it does check versions through regexing on the output of `arm-none-eabi-gcc --version`. I think the matching groups are incorrect, but I don't really know why.

Here's my output of `arm-none-eabi-gcc --version`:
```
$ arm-none-eabi-gcc --version
arm-none-eabi-gcc (GNU Tools for Arm Embedded Processors 8-2018-q4-major) 8.2.1 20181213 (release) [gcc-8-branch revision 267074]
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

`bobbin check` output: 

```
$ bobbin check
    Bobbin 0.8.5
      Rust 1.34.0 (91856ed52 2019-04-10)
     Cargo 1.34.0 (6789d8a0a 2019-04-01)
     Xargo 0.3.13
       GCC Not Found
   OpenOCD 0.10.0
     JLink V6.44g (Compiled Apr 18 2019 17:15:12)
     Bossa 
    Teensy Not Found
  dfu-util 0.9

```

**Comment by jcsoo** [comment]
I will test things out with the 8.2 toolchain to see if I can reproduce. It sounds like a Regex pattern issue.

**Comment by jcsoo** [comment]
Simplified the GCC version detection regex so that it ignores changes within the long description.
