### ISSUE TITLE
Support for bossac offset parameter?

### ISSUE THREAD

**Issue by fionawhim** [bobbin-rs/bobbin-cli#9]
Hi! I'm using Bobbin with some Adafruit M0/M4 devices, and I had to hack it to add in the `-o` parameter to `bossac`.

Apparently since `bossac` 1.9, it defaults to flashing at 0x00000000, but that runs into the locked bootloader.

For M0 devices I needed to add `-o 0x2000` and for M4 I needed `-o 0x4000`.

I was wondering if you’d take a PR to fix this and what approach would be good.

I was thinking either adding the offset as a value on `FeatherDevice` (and having device.rs enumerate more Adafruit boards and fill in this value) or have it as a config that you set in the .bobbin config.

**Comment by jcsoo** [comment]
A PR would be very welcome! I think a command line parameter + .bobbin/config entry would be the best for now, perhaps with autodetection being added later to set the default. That way this will work even for boards that aren't recognized.

**Comment by fionawhim** [comment]
@jcsoo Cool cool. While I’m in there, do you have any feelings about detecting all USB devices with Adafruit’s vendor ID as “FeatherDevice”? Rather than trying to enumerate them?

**Comment by jcsoo** [comment]
I think that makes sense, assuming that most devices using that ID are compatible. If there are devices using Adafruit's vendor ID that don't support Bossac, they can be explicitly blacklisted instead.
